networks:
  testnet:
    sepoila:
      privatekey: ""
      network: "https://eth-sepolia.g.alchemy.com/v2/KE_s6GyLzwP1RJR-FJa8VrcJ_PsxJ6XQ"
      deployedAddress: "0xf030Bb7857cFBE491E8250FFE530458fd28B66a8"
      chainid: "11155111"
    mumbai:
      privatekey: ""
      network: "https://polygon-mumbai.g.alchemy.com/v2/3EBQaaPHYFJv7HXoFcHCkxgpitirS2H5"
      deployedAddress: "0x6aa35ACFDc33b94aaAba0529d38e64aD5d768981"
      chainid: "80001"
    fuji:
      privatekey: ""
      network: "https://api.avax-test.network/ext/bc/C/rpc"
      deployedAddress: "0x5333743490cDdcd14b997bc95744088eBe4dcBB2"
      chainid: "43113"

  mainnet:
    ethereum:
      privatekey: ""
      network: ""
      deployedAddress: ""
      chainid: ""
    polygon:
      network: ""
      deployedAddress: ""
      chainid: ""
    avalanche:
      privatekey: ""
      network: "https://api.avax.network/ext/bc/C/rpc"
      deployedAddress: ""
      chainid: "43114"

database:
  host: "db"
  port: "5432"
  username: "myuser"
  password: "mypassword"
  dbname: "mydatabase"
